doctrine:
    dbal:
        url: '%env(DATABASE_URL)%'
        driver: 'pdo_mysql'
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        types:
            # Add your custom Doctrine types here
            app_hash: Mediagone\Doctrine\Common\Types\Crypto\HashType
            app_hashbcrypt: Mediagone\Doctrine\Common\Types\Crypto\HashBcryptType
            app_name: Mediagone\Doctrine\Common\Types\Text\NameType
            app_email: Mediagone\Doctrine\Common\Types\Web\EmailAddressType
            app_smalluid: Mediagone\SmallUid\Doctrine\SmallUidType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
            string_functions:
                # Add your custom DQL functions here

        mappings:
            App:
                alias: App
                is_bundle: false
                
                type: annotation
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'App\Domain'
                
                #type: xml
                #dir: '%kernel.project_dir%/src/Infrastructure/Adapters/Doctrine/Mappings/Domain'
                #prefix: 'App\Domain'
