# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    #http_method_override: true
    
    error_controller: App\UI\Frontend\Pages\Actions\ErrorAction

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        enabled: true
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'

        gc_probability: 1
        gc_divisor: 100
        gc_maxlifetime: 7776000 # 90 days in seconds

        name: sid
        cookie_domain: '.%app_domain%'
        cookie_lifetime: 31536000
        cookie_samesite: lax
        cookie_secure: auto
    
    #esi: true
    #fragments: true
    php_errors:
        log: true
