parameters:
    security_login_route: 'frontend_security_login'
    security_logout_route: 'frontend_security_logout'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $securityLoginRoute: '%security_login_route%'
            $kernelDebug: '%kernel.debug%'
            

    # Tag controllers classes to make sure services can be injected as action arguments.
    App\UI\Backend\Pages\Actions\:
        resource: '../src/UI/Backend/Pages/Actions/'
        tags: ['controller.service_arguments']

    App\UI\Frontend\Pages\Actions\:
        resource: '../src/UI/Frontend/Pages/Actions/'
        tags: ['controller.service_arguments']

    
    # Load third-party Twig extensions.
    Mediagone\Twig\PowerPack\TwigPowerPackExtension:
        tags: [twig.extension]


    # Loads some UI's classes as services
    App\UI\:
        resource: '../src/UI/*/{Forms,Services}'

    # Use custom error controller
    Symfony\Component\ErrorHandler\ErrorRenderer\ErrorRendererInterface: '@twig.error_renderer.html'
