parameters:
    security_login_route: 'frontend_security_login'
    security_logout_route: 'frontend_security_logout'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $securityLoginRoute: '%security_login_route%'
            $kernelDebug: '%kernel.debug%'
            

    # Tag controllers classes to make sure services can be injected as action arguments.
    app.controllers:
        namespace: App\Application\
        resource: '../src/Application/**/*Action.php'
        tags: ['controller.service_arguments']
    
    # Load third-party Twig extensions.
    Mediagone\Twig\PowerPack\TwigPowerPackExtension:
        tags: [twig.extension]


    # Loads some UI's classes as services
    App\Application\:
        resource: '../src/Application/**/{Forms,Services}'

    # Use custom error controller
    Symfony\Component\ErrorHandler\ErrorRenderer\ErrorRendererInterface: '@twig.error_renderer.html'
