parameters:
    security_login_route: 'security_login'
    security_logout_route: 'security_logout'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $securityLoginRoute: '%security_login_route%'
            

    # Tag controllers classes to make sure services can be injected as action arguments.
    App\UI\Backend\Pages\:
        resource: '../src/UI/Backend/Pages/'
        tags: ['controller.service_arguments']

    App\UI\Frontend\Pages\:
        resource: '../src/UI/Frontend/Pages/'
        tags: ['controller.service_arguments']

    App\UI\Security\Pages\:
        resource: '../src/UI/Security/Pages/'
        tags: ['controller.service_arguments']

    
    # Load third-party Twig extensions.
    Mediagone\Twig\PowerPack\TwigPowerPackExtension:
        tags: [twig.extension]


    # Loads some UI's classes as services
    App\UI\:
        resource: '../src/UI/*/Services'

