services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    # Loads all Infrastructure's classes as services
    App\Infrastructure\:
        resource: ../src/Infrastructure/
